### ISSUE TITLE
request_clause headers need default value

### ISSUE THREAD

**Issue by fishermand46** [thoughtworks/pacto#166]
I'm getting `lib/pacto/stubs/webmock_adapter.rb:95:in `block in strict_details': undefined method `empty?' for nil:NilClass (NoMethodError)` when I try to stub_providers with pacto. I tracked it down to the request_clause.headers being nil.

Test code:
```ruby
contracts = Pacto.load_contracts('spec/fixtures', 'http://localhost:3000', :swagger)
contracts.stub_providers
```
[Here](https://github.com/thoughtworks/pacto/blob/master/lib/pacto/request_clause.rb#L9) you can see that headers in request_clause has no default value. But in the [response clause](https://github.com/thoughtworks/pacto/blob/master/lib/pacto/response_clause.rb#L5), headers defaults to `{}`. I think it should in request_clause as well.

**Comment by maxlinc** [comment]
It makes sense, except that I would like to get away from RequestClause having attributes at all, so that it just an interface that should be implemented by subclasses for specific contract formats (Swagger, RAML, whatever).

I guess I need to find time to make RequestClause abstract and create a subclass for LegacyRequestClause.

**Comment by fishermand46** [comment]
That sounds like a good direction to move. :thumbsup:
